module.exports = {
	SHOW_ERROR: 'SHOW_ERROR',
	HIDE_ERROR: 'HIDE_ERROR',
	SHOW_LOADER: 'SHOW_LOADER',
	HIDE_LOADER: 'HIDE_LOADER',
	SET_TOKEN: 'SET_TOKEN',
	SET_USER: 'SET_USER',
	SET_ROUTE: 'SET_ROUTE',
}
