module.exports = {
	GET_ALL: 'MESSAGE/GET_ALL',
	GET_ONE: 'MESSAGE/GET_ONE',
	GET_NEW: 'MESSAGE/GET_NEW',
	GET_CREATED: 'MESSAGE/GET_CREATED',
	CREATE_NEW: 'MESSAGE/CREATE_NEW',
	REMOVE: 'MESSAGE/REMOVE',
	EDIT: 'MESSAGE/EDIT',
	CLEAR_ALL: 'MESSAGE/CLEAR_ALL',
}
